In [1]:
import numpy as np
scores=[89,56.34,74,89,98]
first_arr=np.array(scores)
print(first_arr)
print(first_arr.dtype) #.dtype returns the data type of array object ---- single dimensional array

[89.   56.34 74.   89.   98.  ]
float64


In [2]:
scores_1=[[34,56,23,89],[11,45,76,34]]
second_arr=np.array(scores_1)
print(second_arr)
print(second_arr.ndim) #ndim gives you the dimensions of an array
print(second_arr.shape) #number of rows, number of columns
print(second_arr.dtype)

[[34 56 23 89]
 [11 45 76 34]]
2
(2, 4)
int32


In [6]:
x=np.zeros(10) #returns an array of zeros
y=np.ones(10) #returns 1

x_upgrade=np.zeros((4,3))
x_arr=np.arange(15)
print(x,y)
print(x_upgrade)
print(x_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
id_matr=np.eye(4) #create a square N*N identity matrix(1 on diagonals and 0 elsewhere)
print(id_matr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
new_arr=np.arange(12)
print(new_arr)
print(new_arr[5])
print(new_arr[4:9])
new_arr[4:9]=99
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5
[4 5 6 7 8]
[ 0  1  2  3 99 99 99 99 99  9 10 11]


In [10]:
modi_arr= new_arr[4:9]
modi_arr[1]=123456
print(new_arr)
modi_arr[:]

[     0      1      2      3     99 123456     99     99     99      9
     10     11]


array([    99, 123456,     99,     99,     99])

In [15]:
matrix_arr=np.array([[3,4,5],[6,7,8],[9,5,1]])
print(matrix_arr)
print(matrix_arr[1])
print(matrix_arr[0][2])#first row and third column
print(matrix_arr[0,2]) #This is same as the above operation

[[3 4 5]
 [6 7 8]
 [9 5 1]]
[6 7 8]
5
5


In [16]:
thie=np.random.randn(5,5)
print(thie)
print(thie.mean())
print(np.mean(thie))
print(thie.sum())

[[-0.05178345 -2.29852361 -0.73063889 -0.4418992   1.33181552]
 [-1.44456505  0.88430182 -2.06812446  0.28008285  1.29642308]
 [-0.98570553  0.17252061 -0.38866807 -0.70773341 -0.63341274]
 [ 0.9502417  -0.12167535 -0.128418   -0.54823433 -0.81672289]
 [-0.38285832 -1.29033957 -1.62454389 -0.74531706  0.6406571 ]]
-0.39412484468025377
-0.39412484468025377
-9.853121117006344


In [18]:
jp=np.arange(12).reshape(4,3)
print('The arrays are: {}'.format(jp))
print('The sum of rows are : {}.'.format(np.sum(jp,axis=0))) #axis=0 gives you sum of columns, axis=1 gives you rows

#remember this zero is for columns and one is for rows

print(jp.sum(1)) #return sum of rows

The arrays are: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The sum of rows are : [18 22 26].
[ 3 12 21 30]


In [20]:
lp=np.random.randn(8)
print(lp)
lp.sort()
print(lp)

[-1.01837692 -0.34153628 -0.4864175  -1.05517872 -1.14102781  0.91356879
  0.18091994 -0.31957638]
[-1.14102781 -1.05517872 -1.01837692 -0.4864175  -0.34153628 -0.31957638
  0.18091994  0.91356879]
